Remove unexpected method argument
Private method '_host_get_by_uuid' expects only two arguments
but in 'host_create' it is getting called with three arguments
which raises:

TypeError: _host_get_by_uuid() takes exactly 2 arguments (3 given)

Change-Id: I96f40d0b8a2828db14e122b581e1ed1d804015c6
Closes-Bug: #1623515